name: Actualizar Publicaciones

on:
  schedule:
    - cron: '0 0 * * 1'  # Ejecuta cada lunes a medianoche
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar el script de scraping
        run: python scraper.py

      - name: Configurar Git y subir cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add publicaciones.json
          git commit -m "Actualizar publicaciones automáticamente" || echo "No hay cambios"
          git push
