name: Generar Publicaciones

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml  # Agregado lxml

      - name: Ejecutar el script de Python
        run: |
          python src/generar_publicaciones.py

      - name: Subir archivo JSON actualizado
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/publicaciones.json
          git commit -m "Actualización del archivo publicaciones.json" || echo "No hay cambios para hacer commit"
          git push
